//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeOnUs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookedEmployees = new HashSet<BookedEmployee>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
        public Nullable<int> StaffNumber { get; set; }
        public Nullable<int> Price { get; set; }
        public string BookingStatus { get; set; }
        public int UserID { get; set; }
        public int CompanyID { get; set; }
        public int PaymentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedEmployee> BookedEmployees { get; set; }
        public virtual Company Company { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
    }
}
